### ISSUE TITLE
Field for gender restrictions

### ISSUE THREAD

**Issue by tomoakley** [good-gym/opendata#1]
Is there a field in your data to distinguish whether a particular GoodGym session is for only one gender, e.g females only like the Cancer Research run? https://www.goodgym.org/races/cancer-research-uk-race-for-life-half-marathon

Alternatively this may not be an issue as there are very few sessions for only one gender. Either way, might be useful to have something to define it in the dataset. Thanks!

**Comment by manzan46** [comment]
Sorry didn't saw this one earlier, 

We don't have this field store somewhere.

**Comment by tomoakley** [comment]
no problem @manzan46, thanks for answering :)
