### ISSUE TITLE
Timezone mismatch between API and website

### ISSUE THREAD

**Issue by lukehesluke** [good-gym/opendata#10]
@manzan46 For example, https://www.goodgym.org/api/happenings/11681 has start date `2018-05-07T18:30:00Z` but the website, https://www.goodgym.org/happenings/get-fit-3cf9a254-5dda-46d8-8155-13e40171be1a, shows "6:30pm". Since we're in British Summer Time, local "6:30pm" is "18:30:00+01:00" i.e. "17:30:00Z"

**Comment by thill-odi** [comment]
This appears to be fixed (`startDates` are now of the form "2020-09-25T10:00:00+01:00")
