### ISSUE TITLE
Higher page size?

### ISSUE THREAD

**Issue by lukehesluke** [good-gym/opendata#11]
Hi,

Love the feed. Love the docs. I just had one suggestion: Would it be possible to increase the page size?

It's currently set to 20, which means that it takes a very long while for crawlers (e.g. crawlers which use a cronjob) to get to the end of it. This means that GoodGym data in these aggregators will be less up to date.

If it was set to 500, that would be ideal. This is also what RPDE recommends (https://www.w3.org/2017/08/realtime-paged-data-exchange/#modified-timestamp-and-id).

You could implement this as a `limit` query parameter, which is [an optional field in RPDE](https://www.w3.org/2017/08/realtime-paged-data-exchange/#modified-timestamp-and-id). e.g. `&limit=500`

Thanks :blush:

Luke

**Comment by metade** [comment]
Thank you for the suggestion, we will consider this.

500 might be too much for our server, but let's see.

**Comment by thill-odi** [comment]
Page limit now appears to be set to 500.
