### ISSUE TITLE
Remove old items past a Retention Period

### ISSUE THREAD

**Issue by lukehesluke** [good-gym/opendata#12]
Hi :relaxed: 

Something that I think would help both us (imin, who are consuming your feed) and yourselves: Implementing a retention period.

This is discussed in the OpenActive developer docs: https://developer.openactive.io/publishing-data/data-feeds/scaling-feeds#retention-period, which suggests setting "old" items (i.e. items whose `startDate` is in the past) to `deleted` and then deleting them "at least 7 days from the point in time at which it transitioned to a "deleted" state".

This would help us immensely as we sometimes need to re-ingest your feed and it takes a very long time to get through it as it includes sessions from 2014- onwards.

Hopefully it would help you as well as you would be free to delete old sessions from the database (or move them to an archive), which may help with costs/performance.

**Comment by metade** [comment]
Hi,

Thanks for the suggestion. Unfortunately we're not able to delete all of our events as we store them for statistics/archival purposes.

However, we'd be happy to only show future events, and hide the past ones.

Can you confirm that we'd need to:
- serve all past events as `deleted` for seven days
- once seven days have passed, then we can stop displaying them in the feed

i.e. we should first display them in the `deleted` state before we can start hiding them.

Also, do you have a suggestion about when old items should be "deleted"? Is it fine to display them in the deleted state as soon as they have passed, or is it best to wait some time before marking them as deleted?

**Comment by lukehesluke** [comment]
> Can you confirm that we'd need to:
> 
> - serve all past events as deleted for seven days
> - once seven days have passed, then we can stop displaying them in the feed

Yes, that's exactly it.

> Is it fine to display them in the deleted state as soon as they have passed

Any amount of time after they've passed is fine including: immediately after, an hour after, etc. As long as there's no timezone issues with BST, immediately after is ideal for us

**Comment by domfennell** [comment]
Hi @metade, hope you're keeping safe and well!

We've just started ingesting your feed again and it seems that there are still items dating back as far as 2014 in the feed. Just wondering if any progress been made on reducing the number of items in your feed by hiding the past events?

Thanks and best,

Dom

**Comment by thill-odi** [comment]
Feed now begins 13 August 2020.
