### ISSUE TITLE
Discrepancy with timestamps and UTC/BST

### ISSUE THREAD

**Issue by tomoakley** [good-gym/opendata#6]
Hi Axel and team,

We've realised that while looking at some other datasets, that your timestamps might be an hour out during British Summer Time. You're providing the data in UTC (ISO 8601 - a `Z` is appended to the end of the timestamp); currently, we are British Summer Time, which is UTC+1, however on your website the times are listed as the same as in the dataset (UTC). Just looking for some clarification on whether these times are in fact correct (they are UTC+1) and the `Z` has been added on in error, or are wrong and out by an hour.

Thanks!

**Comment by domfennell** [comment]
Hi @manzan46, wondered if you had any thoughts on @tomoakley's query above?

Very best,

Dom

**Comment by manzan46** [comment]
Hi, 

Sorry for the delay not sure why I didn't get a notification on the first time. 

I think we might store our data a bit wrongly on this one, everything is store and display in UTC on our website and then we use the ruby method `.iso8601` for the api which append the `z` so I think this is why it's confusing. 
 
Not sure if it's help

**Comment by domfennell** [comment]
Very helpful, @manzan46. Thanks for clarifying. All timings in our Platform match those in your endpoint 👍  Hopefully all remains as expected when BST ends and the clocks go back an hour on 31st October.

Enjoy the rest of your week!
