### ISSUE TITLE
Endpoint 404 error message

### ISSUE THREAD

**Issue by domfennell** [good-gym/opendata#7]
Hi @manzan46, hope you're having a good summer!

I visited your [dataset page](http://data.goodgym.org/) just now to have a look at your OpenActive endpoint and was greeted with a [404 error](https://www.goodgym.org/getHappenings). Has your endpoint changed?

Thanks,

Dom

**Comment by manzan46** [comment]
Hi @domfennell 

Yes we changed the endpoint couple of month ago but forgot to change the OpenActive page ...

Will do that this week.

**Comment by domfennell** [comment]
Nice, @manzan46! Thanks, buddy.

**Comment by ldodds** [comment]
Any chance you can update the link? Looks like the dataset page is still pointing to the old page which is a 404.

**Comment by manzan46** [comment]
@domfennell & @ldodds All fix sorry for the delay

**Comment by ldodds** [comment]
Looks good thanks :+1: 

I think you can close this down now :)
