### ISSUE TITLE
Images missing

### ISSUE THREAD

**Issue by nickevansuk** [good-gym/opendata#8]
Hello @manzan46,

Hope you're having a good summer! Just noticed that all the images in the GoodGym endpoint are set to null? Those images really bring your sessions to life, would be great to have them back!

Thanks,

NIck

**Comment by manzan46** [comment]
Hey @nickevansuk, 

Yeap will fix that shortly, we just migrated our aws and refactored all our images processing including more standard image size 

Ax

**Comment by nickevansuk** [comment]
👍 awesome! Even better 🙂

**Comment by manzan46** [comment]
Hey @nickevansuk it should be back to normal shortly will update documentation with new size next week

**Comment by nickevansuk** [comment]
Great thanks @manzan46 !
